basePath: /
host: localhost:3344
info:
  contact:
    email: xxx
    name: xxx
    url: xxx
  description: This is a demo api
  license:
    name: MIT
    url: xxx
  termsOfService: xxx
  title: DemoApi
  version: '1.1'
paths:
  /v1/user/subscribing:
    put:
      consumes:
      - application/json
      description: Subscribe someone
      operationId: v1-user-subscribing-put
      parameters:
      - description: user id
        in: formData
        name: to
        required: true
        type: integer
      - description: User login token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        '200':
          description: |-
            ```json
            Content-Type: application/json; charset=utf-8
            ```
            ```json
            {
                "code": 200,
                "message": "success"
            }
            ```
        '400':
          description: |-
            "request param error", "request format error"
            ```json
            Content-Type: application/json; charset=utf-8
            ```
            ```json
            {
                "code": 400,
                "message": "request param error"
            }
            ```
        '401':
          description: |-
            "authorization failed", "token has expired"
        '404':
          description: |-
            "user not found"
        '500':
          description: |-
            "subscribe failed"
            ```json
            {
                "code": 500,
                "message": "subscribe failed"
            }
            ```
      security:
      - basicAuth: ''
      summary: Subscribe user
      tags:
      - User
  /v1/user/{uid}/subscriber:
    get:
      consumes:
      - multipart/form-data
      description: Query user's subscribers, return page data
      operationId: v1-user-uid-subscriber-get
      parameters:
      - description: user id
        in: path
        name: uid
        required: true
        type: integer
      - description: page
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '400':
          description: |-
            "request param error"
            ```json
            {
                "code": 200,
                "message": "request param error"
            }
            ```
        '404':
          description: |-
            "user not found"
      summary: User's subscribers
      tags:
      - User
      - Subscribe
swagger: '2.0'
