basePath: /
host: localhost:3344
info:
  contact:
    email: xxx
    name: xxx
    url: xxx
  description: This is a demo api
  license:
    name: MIT
    url: xxx
  termsOfService: xxx
  title: DemoApi
  version: '1.1'
paths:
  /v1/user/subscribing:
    delete:
      consumes:
      - application/json
      description: Unsubscribe someone
      operationId: v1-user-subscribing-delete
      parameters:
      - description: user id
        in: formData
        name: to
        required: true
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: |-
            ```json
            Content-Type: application/json; charset=utf-8
            ```
        '400':
          description: |-
            "request param error", "request format error"
            ```json
            Content-Type: application/json; charset=utf-8
            ```
        '401':
          description: |-
            "authorization failed", "token has expired"
        '404':
          description: |-
            "user not found"
        '500':
          description: |-
            "unsubscribe failed"
            ```json
            {
                "code": 500,
                "message": "unsubscribe failed"
            }
            ```
      security:
      - Jwt: []
      summary: Unsubscribe user
      tags:
      - User
    put:
      consumes:
      - multipart/form-data
      description: Subscribe someone
      operationId: v1-user-subscribing-put
      parameters:
      - description: other header
        in: header
        name: other
        required: false
        type: integer
      - description: user id
        in: formData
        name: to
        required: true
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: |-
            ```json
            {
                "code": 200,
                "message": "success",
                "data": [
                    {
                        "content": "123"
                    },
                    {
                        "content": "456"
                    }
                ]
            }
            ```
        '400':
          description: |-
            "request param error", "request format error"
        '401':
          description: |-
            "authorization failed", "token has expired"
        '404':
          description: |-
            "user not found"
        '500':
          description: |-
            "subscribe failed"
      security:
      - Jwt: []
      summary: Subscribe user
      tags:
      - User
      - Subscribe
  /v1/user/{uid}/subscriber:
    get:
      consumes:
      - multipart/form-data
      description: Query user's subscribers, return page data
      operationId: v1-user-uid-subscriber-get
      parameters:
      - default: 1
        description: user id
        in: path
        name: uid
        required: true
        type: integer
      - default: 1
        description: page
        in: query
        name: page
        required: false
        type: integer
      produces:
      - application/json
      responses:
        '200':
          description: |-
            ```json
            {
                "code": 200,
                "message": "success",
                "data": {
                    "count": 1,
                    "page": 1,
                    "data": [
                        {
                            "uid": 1,
                            "username": "TestUserName",
                            "profile": "TestProfile"
                        }
                    ]
                }
            }
            ```
        '400':
          description: |-
            "request param error"
            ```json
            {
                "code": 400,
                "message": "request param error"
            }
            ```
        '404':
          description: |-
            "user not found"
      summary: User's subscribers
      tags:
      - User
      - Subscribe
securityDefinitions:
  Jwt:
    in: header
    name: Authorization
    type: apiKey
swagger: '2.0'
tags:
- description: User-Controller
  name: User
- description: Sub-Controller
  name: Subscribe
